package com.budgetku.backend.payload.response.invoice;

import com.budgetku.backend.payload.request.AbstractRequest;
import com.budgetku.backend.payload.response.AbstractResponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.util.UUID;

@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Request representing an invoice, including details such as the date of emission, description, associated movement, and file data.")
public class InvoiceResponse extends AbstractResponse {

    @Schema(description = "The date when the invoice was emitted.", example = "2024-11-10", required = true)
    private LocalDate dateOfEmission;

    @Schema(description = "A brief description of the invoice.", example = "Invoice for marketing services", required = true)
    private String description;

    @Schema(description = "UUID of the associated movement, if any.", example = "123e4567-e89b-12d3-a456-426614174000", nullable = true)
    private UUID movementId;

    @Schema(description = "The file content of the invoice, stored as a byte array.", nullable = true)
    private byte[] file;

    @Schema(description = "The associated movement details for this invoice, if available.", nullable = true)
    private MovementResponse movement;

    @Schema(description = "The URL to the receipt generated by Stripe for the transaction", example = "https://pay.stripe.com/receipts/acct_1234/ch_1JN3zd2eZvKYlo2C0Yabc123/rcpt_12345", nullable = true)
    private String stripeReceiptUrl;

    @Schema(description = "The unique document number associated with the payment movement", example = "INV-2024-0001", nullable = true)
    private String movementDocumentNumber;

    @Schema(description = "The key for accessing the invoice file stored in S3. This is used to retrieve or delete the file associated with the invoice.", example = "invoice-1234567890-xyz.pdf", nullable = true)
    private String fileKey;

    @Schema(description = "Base64 encoded content of the invoice file (e.g., PDF), included in the response to display the file.", nullable = true)
    private String fileBase64;
}

